apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: k3d-test
product: k3d
registry: registry-test
k3d:
  v1alpha4Simple:
    kubeAPI:
      hostPort: 3004
      hostIP: "127.0.0.1"
      host: "localhost"
    ports:
    - port: 3005:80 # map the ingress to localhost
      nodeFilters:
        - loadbalancer
---
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: registry-test
port: 5011

